"""
Goethe Institut A1 Wortliste — structured vocabulary data.

Format: (word, article, translation_en, word_type, goethe_example)

word_type codes:
  prep  = preposition
  conj  = conjunction
  adv   = adverb
  verb  = verb (infinitive)
  noun  = noun
  adj   = adjective/adverb
  pron  = pronoun
  num   = numeral
  art   = article
  part  = particle
  interj = interjection
"""

# (word, article_de, translation_en, word_type, goethe_example)
VOCAB_A1: list[tuple[str, str, str, str, str]] = [
    ("ab", "", "from, off, away", "prep", "Ab morgen muss ich arbeiten."),
    ("aber", "", "but, however", "conj", "Ich bin oft im Büro, aber nur für wenige Stunden."),
    ("abfahren", "", "to depart, to leave", "verb", "Wir fahren um zwölf Uhr ab."),
    ("abgeben", "", "to hand in, to give away", "verb", "Ich muss meine Schlüssel abgeben."),
    ("abholen", "", "to pick up, to collect", "verb", "Wann kann ich den Schrank bei dir abholen?"),
    ("der Absender", "", "sender (of a letter)", "noun", "Da ist ein Brief für dich ohne Absender."),
    ("die Adresse", "", "address", "noun", "Können Sie mir seine Adresse sagen?"),
    ("allein", "", "alone, by oneself", "adv", "Er kommt allein."),
    ("alt", "", "old", "adj", "Wie alt sind Sie?"),
    ("das Alter", "", "age", "noun", "Alter: 26 Jahre."),
    ("anbieten", "", "to offer", "verb", "Was darf ich dir anbieten?"),
    ("ankommen", "", "to arrive", "verb", "Wann kommt dieser Zug in Hamburg an?"),
    ("anrufen", "", "to call (by phone)", "verb", "Kann man Sie anrufen?"),
    ("antworten", "", "to answer, to reply", "verb", "Er antwortet nicht."),
    ("das Apartment", "", "apartment, flat", "noun", "Wir haben ein Apartment gemietet."),
    ("der Apfel", "", "apple", "noun", "Ein Pfund Äpfel bitte."),
    ("arbeiten", "", "to work", "verb", "Wo arbeiten Sie?"),
    ("der Arm", "", "arm", "noun", "Mein Arm tut weh."),
    ("der Arzt", "die Ärztin", "doctor, physician", "noun", "Morgen habe ich einen Termin bei meiner Ärztin."),
    ("auf", "", "on, onto, at", "prep", "Die Kinder spielen auf der Straße."),
    ("aufstehen", "", "to get up, to stand up", "verb", "Ich muss immer um vier Uhr aufstehen."),
    ("das Auge", "", "eye", "noun", "Er hat blaue Augen."),
    ("aus", "", "from, out of", "prep", "Er kommt aus Brasilien."),
    ("der Ausflug", "", "excursion, day trip", "noun", "Morgen machen wir einen Ausflug nach Heidelberg."),
    ("der Ausweis", "", "ID card, pass", "noun", "Hier ist mein Ausweis."),
    ("das Auto", "", "car", "noun", "Er kommt mit dem Auto."),
    ("die Autobahn", "", "motorway, highway", "noun", "Wo geht's hier bitte zur Autobahn?"),
    ("das Baby", "", "baby", "noun", "Mein Kind ist noch ein Baby."),
    ("die Bäckerei", "", "bakery", "noun", "Ich geh mal schnell zur Bäckerei."),
    ("das Bad", "", "bathroom, bath", "noun", "Wir haben kein großes Bad."),
    ("die Bahn", "", "train, railway", "noun", "Wir fahren lieber mit der Bahn."),
    ("der Bahnhof", "", "train station", "noun", "Komme ich hier zum Bahnhof?"),
    ("der Balkon", "", "balcony", "noun", "Die Wohnung hat auch einen kleinen Balkon."),
    ("die Banane", "", "banana", "noun", "Drei Bananen, bitte!"),
    ("die Bank", "", "bank", "noun", "Die Bank schließt schon um vier Uhr."),
    ("der Bauch", "", "stomach, belly", "noun", "Seit gestern tut mir der Bauch weh."),
    ("der Baum", "", "tree", "noun", "Vorsicht, fahr nicht an den Baum!"),
    ("bedeuten", "", "to mean, to signify", "verb", "Was bedeutet das Wort?"),
    ("beginnen", "", "to begin, to start", "verb", "Das Spiel beginnt um 15.30 Uhr."),
    ("das Bein", "", "leg", "noun", "Mein rechtes Bein tut weh."),
    ("das Beispiel", "", "example", "noun", "Kannst du mir ein Beispiel sagen?"),
    ("bekommen", "", "to receive, to get", "verb", "Haben Sie meinen Brief bekommen?"),
    ("bestellen", "", "to order", "verb", "Wir möchten bestellen, bitte."),
    ("besuchen", "", "to visit", "verb", "Darf ich dich besuchen?"),
    ("das Bett", "", "bed", "noun", "Wir brauchen noch ein Kinderbett."),
    ("bezahlen", "", "to pay", "verb", "Wo muss ich bezahlen?"),
    ("das Bier", "", "beer", "noun", "Noch ein Bier bitte."),
    ("das Bild", "", "picture, image, photo", "noun", "Hast du ein Bild von deinem Sohn?"),
    ("billig", "", "cheap, inexpensive", "adj", "Die Jacke kostet nur 10 Euro! Die ist aber billig!"),
    ("die Birne", "", "pear", "noun", "Ein Kilo Birnen, bitte!"),
    ("bitte", "", "please / you're welcome", "part", "Eine Tasse Kaffee, bitte!"),
    ("bleiben", "", "to stay, to remain", "verb", "Ich bleibe heute zu Hause."),
    ("der Bleistift", "", "pencil", "noun", "Hast du einen Bleistift?"),
    ("die Blume", "", "flower", "noun", "Gefallen dir die Blumen?"),
    ("das Brot", "", "bread", "noun", "Haben Sie auch Weißbrot?"),
    ("das Brötchen", "", "bread roll", "noun", "Möchtest du Brötchen zum Frühstück?"),
    ("der Bruder", "", "brother", "noun", "Sein Bruder arbeitet auch hier."),
    ("das Buch", "", "book", "noun", "Gute Bücher sind oft sehr teuer."),
    ("der Buchstabe", "", "letter (of the alphabet)", "noun", "Diesen Buchstaben gibt es in meiner Sprache nicht."),
    ("buchstabieren", "", "to spell (out)", "verb", "Bitte buchstabieren Sie Ihren Namen."),
    ("der Bus", "", "bus", "noun", "Wann kommt der nächste Bus?"),
    ("die Butter", "", "butter", "noun", "Für mich bitte ein Brötchen mit Butter und Käse."),
    ("das Café", "", "café, coffee shop", "noun", "Sollen wir uns im Café treffen?"),
    ("der Chef", "die Chefin", "boss, manager", "noun", "Wir haben eine neue Chefin."),
    ("der Computer", "", "computer", "noun", "Wann bekommst du deinen neuen Computer?"),
    ("die Dame", "", "lady, madam", "noun", "Sehr geehrte Damen und Herren!"),
    ("danken", "", "to thank", "verb", "Ich danke Ihnen für die Einladung."),
    ("das Datum", "", "date (calendar)", "noun", "Bitte schreiben Sie noch das Datum auf das Formular."),
    ("dauern", "", "to last, to take (time)", "verb", "Wie lange dauert der Film?"),
    ("die Disco", "", "disco, nightclub", "noun", "Heute abend gehen wir in die Disco tanzen."),
    ("der Doktor", "", "doctor", "noun", "Meine Tochter ist krank. Wir gehen zum Doktor."),
    ("das Doppelzimmer", "", "double room", "noun", "Wollen Sie ein Doppelzimmer oder ein Einzelzimmer?"),
    ("das Dorf", "", "village", "noun", "Meine Familie lebt in einem Dorf."),
    ("drucken", "", "to print", "verb", "Bitte drucke das Formular für mich."),
    ("durch", "", "through, via", "prep", "Am besten gehen Sie durch die Breite Straße."),
    ("dürfen", "", "to be allowed to, may", "verb", "Sie dürfen hier nicht rauchen."),
    ("der Durst", "", "thirst", "noun", "Hast du etwas zu trinken? Ich habe großen Durst."),
    ("die Dusche", "", "shower", "noun", "Unsere Wohnung hat nur eine Dusche."),
    ("die Ecke", "", "corner", "noun", "An der nächsten Ecke links."),
    ("das Ei", "", "egg", "noun", "Möchtest du ein Ei zum Frühstück?"),
    ("einladen", "", "to invite", "verb", "Darf ich Sie zu einem Kaffee einladen?"),
    ("die Eltern", "", "parents", "noun", "Meine Eltern leben in Spanien."),
    ("die E-Mail", "", "email", "noun", "Ich habe Ihre E-Mail nicht bekommen."),
    ("essen", "", "to eat", "verb", "Was gibt es zu essen?"),
    ("fahren", "", "to drive, to travel", "verb", "Ich fahre mit dem Auto zur Arbeit."),
    ("die Fahrkarte", "", "ticket (transport)", "noun", "Hast du schon eine Fahrkarte?"),
    ("das Fahrrad", "", "bicycle, bike", "noun", "Fährst du mit dem Fahrrad oder mit dem Auto?"),
    ("die Familie", "", "family", "noun", "Meine Familie lebt in Spanien."),
    ("der Familienname", "", "surname, family name", "noun", "Meine Familiennamen sind García González."),
    ("die Farbe", "", "colour", "noun", "Die Farbe gefällt mir gut."),
    ("feiern", "", "to celebrate", "verb", "Wir feiern heute meinen Geburtstag."),
    ("fehlen", "", "to be missing, to ache", "verb", "Was fehlt Ihnen?"),
    ("der Fehler", "", "mistake, error", "noun", "Diesen Fehler mache ich immer."),
    ("fernsehen", "", "to watch TV", "verb", "Wollen wir heute Abend mal fernsehen?"),
    ("fertig", "", "finished, ready, done", "adj", "Bist du fertig?"),
    ("das Feuer", "", "fire, flame", "noun", "Haben Sie Feuer?"),
    ("das Fieber", "", "fever, temperature", "noun", "Mein Mann hat noch immer Fieber."),
    ("der Film", "", "film, movie", "noun", "Ich möchte gern diesen Film sehen."),
    ("finden", "", "to find", "verb", "Wir müssen den Schlüssel finden."),
    ("die Firma", "", "company, firm", "noun", "Er arbeitet jetzt bei einer anderen Firma."),
    ("der Fisch", "", "fish", "noun", "Ich esse gern Fisch."),
    ("die Flasche", "", "bottle", "noun", "Eine Flasche Bier, bitte."),
    ("das Fleisch", "", "meat", "noun", "Fleisch mag ich nicht."),
    ("fliegen", "", "to fly", "verb", "Ich fliege nicht gern. Deshalb fahre ich mit dem Zug."),
    ("der Flughafen", "", "airport", "noun", "Kannst du mich zum Flughafen bringen?"),
    ("das Flugzeug", "", "aeroplane, airplane", "noun", "Das Flugzeug aus Berlin kommt heute später an."),
    ("das Formular", "", "form (document)", "noun", "Sie müssen dieses Formular ausfüllen."),
    ("das Foto", "", "photo, photograph", "noun", "Darf ich ein Foto machen?"),
    ("fragen", "", "to ask, to question", "verb", "Er möchte Sie etwas fragen."),
    ("die Frau", "", "woman, wife, Mrs.", "noun", "Das ist Frau Becker."),
    ("frei", "", "free, available, vacant", "adj", "Ist der Platz noch frei?"),
    ("die Freizeit", "", "free time, leisure", "noun", "In meiner Freizeit spiele ich oft Fußball."),
    ("der Freund", "die Freundin", "friend, boyfriend/girlfriend", "noun", "Das ist ein Freund von mir."),
    ("frühstücken", "", "to have breakfast", "verb", "Am Sonntag frühstücke ich gern im Bett."),
    ("das Frühstück", "", "breakfast", "noun", "Möchtest du ein Ei zum Frühstück?"),
    ("für", "", "for", "prep", "Das ist für Sie."),
    ("der Fuß", "", "foot", "noun", "Der linke Fuß tut mir weh."),
    ("der Fußball", "", "football, soccer", "noun", "Spielt ihr gerne Fußball?"),
    ("der Garten", "", "garden", "noun", "Wir haben leider keinen Garten."),
    ("geben", "", "to give", "verb", "Kannst du mir bitte deinen Kugelschreiber geben?"),
    ("der Geburtstag", "", "birthday", "noun", "Herzlichen Glückwunsch zum Geburtstag!"),
    ("gefallen", "", "to like, to please", "verb", "Das gefällt mir."),
    ("gehen", "", "to go, to walk", "verb", "Wie geht's?"),
    ("das Geld", "", "money", "noun", "Hast du noch Geld?"),
    ("das Gemüse", "", "vegetables", "noun", "Gemüse brauchen wir auch noch."),
    ("das Gepäck", "", "luggage, baggage", "noun", "Wollen Sie Ihr Gepäck mitnehmen?"),
    ("das Geschäft", "", "shop, store, business", "noun", "Die Geschäfte schließen um 18.30 Uhr."),
    ("das Geschenk", "", "gift, present", "noun", "Danke für das schöne Geschenk."),
    ("die Geschwister", "", "siblings (brothers and sisters)", "noun", "Ich habe leider keine Geschwister."),
    ("gestern", "", "yesterday", "adv", "Gestern war ich krank."),
    ("das Getränk", "", "drink, beverage", "noun", "Mein Lieblingsgetränk ist Tomatensaft."),
    ("das Glas", "", "glass", "noun", "Bitte noch ein Glas Wein!"),
    ("glauben", "", "to believe, to think", "verb", "Sie können mir glauben, es ist so."),
    ("das Glück", "", "luck, happiness", "noun", "Viel Glück!"),
    ("groß", "", "big, large, tall", "adj", "Mein Bruder und ich sind gleich groß."),
    ("die Großeltern", "", "grandparents", "noun", "Meine Großeltern leben in Japan."),
    ("die Gruppe", "", "group", "noun", "Die erste Gruppe beginnt um 16 Uhr."),
    ("gut", "", "good, well", "adj", "Das finde ich gut."),
    ("das Haar", "", "hair", "noun", "Sie hat lange Haare."),
    ("haben", "", "to have", "verb", "Ich habe ein neues Auto."),
    ("das Hähnchen", "", "chicken", "noun", "Ein Hähnchen mit Pommes bitte!"),
    ("hallo", "", "hello, hi", "interj", "Hallo Inge! Wie geht's?"),
    ("die Hand", "", "hand", "noun", "Er gibt mir die Hand."),
    ("das Handy", "", "mobile phone, cell phone", "noun", "In der Schule bitte die Handys ausmachen!"),
    ("das Haus", "", "house", "noun", "In welchem Haus wohnst du?"),
    ("die Hausaufgabe", "", "homework", "noun", "Kannst du mir bei den Hausaufgaben helfen?"),
    ("helfen", "", "to help", "verb", "Können Sie mir helfen, bitte?"),
    ("heiraten", "", "to marry, to get married", "verb", "Meine Schwester heiratet einen Japaner."),
    ("heißen", "", "to be called, to be named", "verb", "Ich heiße Charlotte Meier."),
    ("hell", "", "bright, light", "adj", "Im Sommer ist es bis 21 Uhr hell."),
    ("der Herd", "", "cooker, stove", "noun", "In der neuen Küche fehlt noch der Herd."),
    ("das Hobby", "", "hobby", "noun", "Meine Hobbys sind Wandern und Schwimmen."),
    ("hören", "", "to hear, to listen", "verb", "Hör mal! Was ist das?"),
    ("das Hotel", "", "hotel", "noun", "Im Urlaub sind wir in einem Hotel am Meer."),
    ("der Hund", "", "dog", "noun", "Der Hund ist noch jung."),
    ("der Hunger", "", "hunger", "noun", "Ich habe Hunger! Wann ist das Essen fertig?"),
    ("immer", "", "always", "adv", "Frau Bast kommt immer zu spät."),
    ("das Internet", "", "internet", "noun", "Das findest du im Internet."),
    ("die Jacke", "", "jacket", "noun", "Zieh dir eine Jacke an. Es ist kalt."),
    ("jetzt", "", "now", "adv", "Jetzt machen wir eine Pause."),
    ("der Job", "", "job", "noun", "Jenny hat einen neuen Job bei der Post."),
    ("jung", "", "young", "adj", "Claudia ist 21. – Was? Noch so jung?"),
    ("der Kaffee", "", "coffee", "noun", "Zum Frühstück trinke ich immer Kaffee."),
    ("kaputt", "", "broken, out of order", "adj", "Das Glas war teuer. Es geht sehr leicht kaputt."),
    ("die Karte", "", "card, map, ticket", "noun", "Ich schreibe meinen Bekannten eine Karte aus dem Urlaub."),
    ("die Kartoffel", "", "potato", "noun", "Für Pommes frites braucht man Kartoffeln."),
    ("kaufen", "", "to buy", "verb", "Tim kauft sich ein neues Auto."),
    ("kennen", "", "to know (a person/place)", "verb", "Kennen Sie diese Frau?"),
    ("das Kind", "", "child", "noun", "Wie viele Kinder haben Sie?"),
    ("der Kindergarten", "", "kindergarten, nursery school", "noun", "Die kleine Laura geht schon in den Kindergarten."),
    ("das Kino", "", "cinema, movie theater", "noun", "Wir sehen heute Abend im Kino einen schönen Film."),
    ("klar", "", "clear, of course", "adj", "Kommst du mit? – Klar!"),
    ("die Kleidung", "", "clothing, clothes", "noun", "Wo finde ich Kleidung?"),
    ("klein", "", "small, little, short", "adj", "Eltville ist eine kleine Stadt am Rhein."),
    ("kochen", "", "to cook", "verb", "Herr Georgi kann gut kochen."),
    ("der Koffer", "", "suitcase", "noun", "Ist das Ihr Koffer?"),
    ("der Kollege", "die Kollegin", "colleague, coworker", "noun", "Wie heißt die neue Kollegin?"),
    ("kommen", "", "to come", "verb", "Woher kommen Sie?"),
    ("können", "", "to be able to, can", "verb", "Ich kann Deutsch und Russisch."),
    ("das Konto", "", "bank account", "noun", "Das Geld überweisen wir auf Ihr Konto."),
    ("der Kopf", "", "head", "noun", "Mein Kopf tut weh!"),
    ("kosten", "", "to cost", "verb", "Wie viel kostet das?"),
    ("krank", "", "ill, sick", "adj", "Ich kann heute nicht zur Arbeit kommen, ich bin krank."),
    ("die Küche", "", "kitchen", "noun", "Der neue Herd kommt in die Küche."),
    ("der Kuchen", "", "cake", "noun", "Ich nehme ein Stück Kuchen."),
    ("der Kühlschrank", "", "fridge, refrigerator", "noun", "Haben wir noch Milch? – Ja, im Kühlschrank."),
    ("der Kurs", "", "course, class", "noun", "Der Deutschkurs geht bis zum Sommer."),
    ("lachen", "", "to laugh", "verb", "Die Kinder lachen viel."),
    ("das Land", "", "country, land", "noun", "Italien ist ein schönes Land."),
    ("lang", "", "long, tall", "adj", "Die Jeans ist zu lang."),
    ("laufen", "", "to run, to walk", "verb", "Ich möchte nicht Auto fahren, ich möchte laufen."),
    ("leben", "", "to live", "verb", "Sie lebt bei ihrer Schwester."),
    ("die Lebensmittel", "", "food, groceries", "noun", "Lebensmittel bekommen Sie im Supermarkt."),
    ("legen", "", "to put, to lay", "verb", "Legen Sie das Buch auf den Tisch."),
    ("der Lehrer", "die Lehrerin", "teacher", "noun", "Unsere Deutschlehrerin heißt Frau Müller."),
    ("leicht", "", "light, easy", "adj", "Der Koffer ist leicht."),
    ("leider", "", "unfortunately", "adv", "Leider kann ich nicht kommen."),
    ("leise", "", "quiet, softly", "adj", "Seid leise. Die anderen schlafen schon."),
    ("lernen", "", "to learn, to study", "verb", "Wie lange lernen Sie schon Deutsch?"),
    ("lesen", "", "to read", "verb", "Ich lese ein Buch von García Márquez."),
    ("die Leute", "", "people", "noun", "In der Disko sind viele Leute."),
    ("das Licht", "", "light", "noun", "Wo macht man hier das Licht an?"),
    ("lieben", "", "to love", "verb", "Ich liebe dich!"),
    ("das Lied", "", "song", "noun", "Welches ist dein Lieblingslied?"),
    ("liegen", "", "to lie (be situated)", "verb", "Um neun Uhr liegt Judith noch im Bett."),
    ("links", "", "left, to the left", "adv", "Gehen Sie die nächste Straße links."),
    ("das Mädchen", "", "girl", "noun", "Familie Kurz bekommt ein Baby. – Mädchen?"),
    ("machen", "", "to do, to make", "verb", "Was machst du heute Abend?"),
    ("der Mann", "", "man, husband", "noun", "Mein Mann arbeitet bei der Polizei."),
    ("das Meer", "", "sea, ocean", "noun", "Wir machen Urlaub am Meer."),
    ("mieten", "", "to rent", "verb", "Ich möchte ein Auto mieten."),
    ("die Miete", "", "rent", "noun", "Die Miete für diese Wohnung ist 600 Euro."),
    ("die Milch", "", "milk", "noun", "Die Milch steht im Kühlschrank."),
    ("die Möbel", "", "furniture", "noun", "Sind die Möbel neu?"),
    ("möchten", "", "would like to", "verb", "Was möchten Sie trinken?"),
    ("morgen", "", "tomorrow", "adv", "Morgen beginnt die Schule um 10 Uhr."),
    ("müde", "", "tired", "adj", "Ich bin müde. Ich gehe schlafen."),
    ("müssen", "", "must, to have to", "verb", "Ich muss jeden Tag von 8 Uhr bis 18 Uhr arbeiten."),
    ("die Mutter", "", "mother", "noun", "Frau Berghäuser ist die Mutter von Michaela."),
    ("nach", "", "after, to, towards", "prep", "Ich gehe jetzt nach Hause."),
    ("der Name", "", "name", "noun", "Mein Name ist Thomas Schmidt."),
    ("nehmen", "", "to take", "verb", "Heute gibt es Hähnchen. Das nehme ich."),
    ("neu", "", "new", "adj", "Ich bin der neue Kollege."),
    ("nie", "", "never", "adv", "Er kommt nie pünktlich."),
    ("noch", "", "still, yet, another", "adv", "Vielleicht kommt er noch."),
    ("die Nummer", "", "number", "noun", "Sie haben Zimmer Nummer zwölf."),
    ("oben", "", "above, upstairs", "adv", "Ich wohne oben."),
    ("das Obst", "", "fruit", "noun", "Im Sommer ist das Obst billig."),
    ("öffnen", "", "to open", "verb", "Ich öffne die Tür."),
    ("oft", "", "often", "adv", "Petra treffe ich oft."),
    ("die Oma", "", "grandma, grandmother", "noun", "Meine Oma ist schon tot."),
    ("der Opa", "", "grandpa, grandfather", "noun", "Mein Opa heißt Hans."),
    ("das Papier", "", "paper", "noun", "Hier sind Papier und Bleistift."),
    ("der Partner", "die Partnerin", "partner", "noun", "Sie ist meine Partnerin."),
    ("die Party", "", "party", "noun", "Heute Abend machen wir eine Party."),
    ("der Pass", "", "passport", "noun", "Im Hotel brauchst du deinen Pass."),
    ("die Pause", "", "break, pause", "noun", "Von 12.00 bis 12.30 Uhr haben wir Mittagspause."),
    ("der Plan", "", "plan, map", "noun", "Ich kaufe mir einen Stadtplan."),
    ("der Platz", "", "place, seat, square", "noun", "Tut mir leid, der Platz ist besetzt."),
    ("die Polizei", "", "police", "noun", "Holen Sie die Polizei!"),
    ("die Post", "", "post office, mail", "noun", "Wo ist die Post, bitte?"),
    ("der Preis", "", "price, prize", "noun", "Die Preise sind hoch."),
    ("das Problem", "", "problem", "noun", "Mein Problem ist die Sprache."),
    ("die Prüfung", "", "exam, test", "noun", "Die Prüfung ist am Montag um 8.00 Uhr."),
    ("pünktlich", "", "punctual, on time", "adj", "Der Bus fährt pünktlich um acht Uhr."),
    ("rechts", "", "right, to the right", "adv", "Die Schillerstraße ist hier rechts."),
    ("regnen", "", "to rain", "verb", "Heute regnet es."),
    ("der Reis", "", "rice", "noun", "Ich esse gern Reis."),
    ("reisen", "", "to travel", "verb", "Ich reise gern."),
    ("das Restaurant", "", "restaurant", "noun", "Wir essen heute in einem Restaurant."),
    ("richtig", "", "correct, right", "adj", "Habe ich das richtig verstanden?"),
    ("ruhig", "", "quiet, calm", "adj", "Ich möchte ein ruhiges Zimmer."),
    ("der Saft", "", "juice", "noun", "Möchtest du einen Apfelsaft?"),
    ("sagen", "", "to say, to tell", "verb", "Sag mal, wie geht es dir denn?"),
    ("der Salat", "", "salad, lettuce", "noun", "Wie schmeckt dir der Salat?"),
    ("der Satz", "", "sentence", "noun", "Dieser Satz ist sehr einfach."),
    ("die S-Bahn", "", "suburban/city train", "noun", "Ich nehme lieber die S-Bahn."),
    ("schicken", "", "to send", "verb", "Bitte schicken Sie mir eine E-Mail."),
    ("schlafen", "", "to sleep", "verb", "Ich schlafe meistens acht Stunden."),
    ("schlecht", "", "bad, ill, poorly", "adj", "Mir ist schlecht!"),
    ("schließen", "", "to close, to shut", "verb", "Bitte, schließen Sie die Tür."),
    ("der Schlüssel", "", "key", "noun", "Ich gebe Ihnen noch den Zimmerschlüssel."),
    ("schmecken", "", "to taste, to taste good", "verb", "Schmeckt das gut?"),
    ("schnell", "", "fast, quick", "adj", "Er fährt schnell."),
    ("schön", "", "beautiful, nice, lovely", "adj", "Schönen Urlaub!"),
    ("der Schrank", "", "cupboard, wardrobe", "noun", "Die Gläser stehen im Schrank."),
    ("schreiben", "", "to write", "verb", "Er schreibt jeden Tag fünfzig E-Mails."),
    ("der Schuh", "", "shoe", "noun", "Zieh die Schuhe aus!"),
    ("die Schule", "", "school", "noun", "Meine Tochter geht schon in die Schule."),
    ("schwer", "", "heavy, difficult", "adj", "Ist Ihr Gepäck sehr schwer?"),
    ("die Schwester", "", "sister", "noun", "Meine Schwester kommt am Dienstag."),
    ("schwimmen", "", "to swim", "verb", "Ich schwimme jeden Tag einen Kilometer."),
    ("sehen", "", "to see", "verb", "Ich kann dich nicht sehen."),
    ("sein", "", "to be", "verb", "Ich bin dreiundzwanzig."),
    ("seit", "", "since, for (time)", "prep", "Ich wohne seit drei Jahren in Köln."),
    ("sich vorstellen", "", "to introduce oneself", "verb", "Können Sie sich bitte vorstellen?"),
    ("sitzen", "", "to sit", "verb", "Wo sitzen Sie?"),
    ("der Sohn", "", "son", "noun", "Das ist Hans, mein Sohn."),
    ("sollen", "", "to be supposed to, should", "verb", "Soll ich kommen?"),
    ("die Sonne", "", "sun", "noun", "Die Sonne scheint."),
    ("spät", "", "late", "adj", "Es ist schon spät, ich muss gehen."),
    ("spielen", "", "to play", "verb", "Die Kinder spielen draußen."),
    ("der Sport", "", "sport", "noun", "Ich mache viel Sport."),
    ("die Sprache", "", "language", "noun", "Welche Sprachen sprichst du?"),
    ("sprechen", "", "to speak, to talk", "verb", "Kann ich mit Herrn Klein sprechen?"),
    ("die Stadt", "", "city, town", "noun", "Heidelberg ist eine alte Stadt."),
    ("stehen", "", "to stand", "verb", "Der Bus steht schon an der Haltestelle."),
    ("die Straße", "", "street, road", "noun", "In welcher Straße wohnen Sie?"),
    ("studieren", "", "to study (at university)", "verb", "Ich studiere in Mainz."),
    ("suchen", "", "to look for, to search", "verb", "Suchst du etwas?"),
    ("tanzen", "", "to dance", "verb", "Tanzen Sie gern?"),
    ("die Tasche", "", "bag, pocket", "noun", "Ich habe die Schlüssel in der Tasche."),
    ("das Taxi", "", "taxi, cab", "noun", "Es gibt heute keinen Bus mehr. Er fährt mit dem Taxi."),
    ("der Tee", "", "tea", "noun", "Ich trinke morgens immer Tee."),
    ("telefonieren", "", "to phone, to call", "verb", "Darf ich mal telefonieren?"),
    ("der Termin", "", "appointment", "noun", "Am besten machen wir sofort einen Termin."),
    ("teuer", "", "expensive", "adj", "Das ist mir zu teuer."),
    ("der Tisch", "", "table", "noun", "Die Fotos liegen auf dem Tisch."),
    ("die Tochter", "", "daughter", "noun", "Das ist meine Tochter Katharina."),
    ("die Toilette", "", "toilet, restroom", "noun", "Wo ist die Toilette, bitte?"),
    ("die Tomate", "", "tomato", "noun", "Die Tomate ist noch grün."),
    ("treffen", "", "to meet", "verb", "Wir treffen uns immer freitags."),
    ("trinken", "", "to drink", "verb", "Möchtest du etwas trinken?"),
    ("der Urlaub", "", "holiday, vacation", "noun", "Ich nehme im September Urlaub."),
    ("der Vater", "", "father", "noun", "Mein Vater ist Arbeiter."),
    ("verheiratet", "", "married", "adj", "Ich bin verheiratet und habe drei Kinder."),
    ("verkaufen", "", "to sell", "verb", "Er verkauft sein altes Auto."),
    ("verstehen", "", "to understand", "verb", "Können Sie mich verstehen?"),
    ("viel", "", "much, a lot, many", "adj", "Hier regnet es viel."),
    ("wann", "", "when", "adv", "Wann bist du fertig?"),
    ("warten", "", "to wait", "verb", "Können Sie ein paar Minuten warten?"),
    ("warum", "", "why", "adv", "Warum kommt er nicht?"),
    ("waschen", "", "to wash", "verb", "Ich muss morgen waschen."),
    ("das Wasser", "", "water", "noun", "Ein Glas Wasser, bitte."),
    ("der Wein", "", "wine", "noun", "Nein danke, ich möchte keinen Wein."),
    ("die Welt", "", "world", "noun", "Es gibt viele Probleme auf der Welt."),
    ("werden", "", "to become, will", "verb", "Mein Sohn will Arzt werden."),
    ("das Wetter", "", "weather", "noun", "Wir hatten schlechtes Wetter."),
    ("wie", "", "how, like, as", "adv", "Wie heißt du?"),
    ("wohnen", "", "to live, to reside", "verb", "Ich wohne in München."),
    ("die Wohnung", "", "flat, apartment", "noun", "Seit wann haben Sie diese Wohnung?"),
    ("wollen", "", "to want to", "verb", "Wollen Sie einen Kaffee trinken?"),
    ("das Wort", "", "word", "noun", "Ich kenne das Wort nicht."),
    ("zahlen", "", "to pay", "verb", "Zahlen, bitte!"),
    ("die Zeit", "", "time", "noun", "Ich habe heute keine Zeit."),
    ("die Zeitung", "", "newspaper", "noun", "Ich lese gern Zeitung."),
    ("das Zimmer", "", "room", "noun", "Das Zimmer ist groß."),
    ("der Zug", "", "train", "noun", "Ich fahre gern mit dem Zug."),
    ("zurück", "", "back, return", "adv", "Einmal Frankfurt und zurück."),
    ("zusammen", "", "together", "adv", "Sollen wir zusammen essen gehen?"),
]
